# 1. Server Config
server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mcdb?characterEncoding=utf8
    username: ENC(fYs/Vy061CXL8OWqFyk8tg==)
    password: ENC(8AgoBTucPbZpCjsWw11uDQ==)

# 3. Mybatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 3. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 4. User Define App
app:
  key:
    wkey: ENC(Z/iDgLx1J/KFF7LMZneNJzA8rD5wG4kyMH+aMIMnop55VBcXKHxQom3mrPjqYk/GRY5vdB/hIhVN9ggeVON+bX/g0DyWcxzMmXT0AMYgNAzZPulzu98OdTmDwVD/tIzITBQVSNm/nPcxxfPzMsi68A==)
    wkey2: ENC(O1E5fpcaV+/9j8tu0P5YVC7R8+3QFNo5MYtlOm+It0QaXOAR2thzmsNzeKxH0aXc)
    algo: PBEWithMD5AndDES  # Twoway
    skey: mykey             # Twoway
  dir:
    imgdir: file:///D:/spring25/imgs/  # 화면 출력 용
    uploadimgdir: D:/spring25/imgs/    # 파일 Write 용
  url:
   websocket-server-url: http://127.0.0.1:8088


